// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Sequence struct {
	ID                   uuid.UUID          `db:"id"`
	Name                 string             `db:"name"`
	OpenTrackingEnabled  bool               `db:"open_tracking_enabled"`
	ClickTrackingEnabled bool               `db:"click_tracking_enabled"`
	CreatedAt            pgtype.Timestamptz `db:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at"`
}

type SequenceStep struct {
	ID                    uuid.UUID          `db:"id"`
	SequenceID            uuid.UUID          `db:"sequence_id"`
	DaysAfterPreviousStep int32              `db:"days_after_previous_step"`
	EmailSubject          string             `db:"email_subject"`
	EmailContent          string             `db:"email_content"`
	Ordering              float32            `db:"ordering"`
	CreatedAt             pgtype.Timestamptz `db:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at"`
}
